Vagrant.configure("2") do |config|
  config.vm.box = "benton-gray/centos-8"

  # Packer install vagrant-vbguest plugins
  config.vm.hostname = "centos-8"
  if ENV["VM_SYNCED_FOLDER"]
    config.vm.synced_folder ENV["VM_SYNCED_FOLDER"], "/development"
  end
  
  config.vm.provider "virtualbox" do |v|
    v.name         = "centos-8"
    v.cpus         = ENV["VM_CPUS"]   ? ENV["VM_CPUS"]   : 1
    v.memory       = ENV["VM_MEMORY"] ? ENV["VM_MEMORY"] : 512
    v.linked_clone = true
  end
  
  config.trigger.after :up do |trigger|
    trigger.info = "Machine is up! "\
                   "Initialize with "\
                   "'vagrant provision --provision-with init' :)"
  end
  
  config.vm.network "forwarded_port", 
    guest: 3000, 
    host: 3000, 
    auto_correct: true
end