Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Packer install vagrant-vbguest plugins
  config.vm.hostname = "focal64"
  if ENV["VM_SYNCED_FOLDER"]
    config.vm.synced_folder ENV["VM_SYNCED_FOLDER"], "/development"
  end

  
  config.vm.provider "virtualbox" do |v|
    v.name         = "focal64"
    v.cpus         = ENV["VM_CPUS"]   ? ENV["VM_CPUS"]   : 4
    v.memory       = ENV["VM_MEMORY"] ? ENV["VM_MEMORY"] : 4096
    v.linked_clone = true
  end
  
  config.trigger.after :up do |trigger|
    trigger.info = "Machine is up! "\
                   "Initialize with "\
                   "'vagrant provision --provision-with init' :)"
  end
  
  config.vm.network "forwarded_port", 
    guest: 1313, 
    host: 3000, 
    auto_correct: true
end